from datetime import datetime
import html
import os


def generate_report(target, vulns, dumped_data=None):
    """
    target       : URL mục tiêu
    vulns        : list vulnerabilities
    dumped_data  : dict dữ liệu dump (theo URL hiện tại)
    """

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"Security_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"

    # ================= HEADER =================
    report_html = f"""
<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="utf-8">
<title>Security Audit Report</title>
<style>
    body {{
        font-family: 'Segoe UI', sans-serif;
        margin: 40px;
        background: #f4f6f8;
    }}
    h1, h2, h3, h4 {{
        margin-top: 20px;
    }}
    .header {{
        background: #2c3e50;
        color: white;
        padding: 25px;
        border-radius: 10px;
    }}
    .vuln-card {{
        background: white;
        padding: 20px;
        margin: 15px 0;
        border-radius: 10px;
        border-left: 6px solid #e74c3c;
        box-shadow: 0 2px 6px rgba(0,0,0,0.1);
    }}
    table {{
        border-collapse: collapse;
        width: 100%;
        margin-top: 10px;
    }}
    th, td {{
        border: 1px solid #ccc;
        padding: 6px 10px;
        font-size: 13px;
    }}
    th {{
        background: #34495e;
        color: white;
    }}
    .data-box {{
        background: #ecf0f1;
        padding: 15px;
        border-radius: 6px;
        font-family: Consolas, monospace;
        margin-bottom: 15px;
    }}
    .footer {{
        margin-top: 40px;
        font-size: 12px;
        color: #666;
        text-align: center;
    }}
</style>
</head>
<body>

<div class="header">
    <h1>Security Audit Report</h1>
    <p><b>Mục tiêu:</b> {html.escape(target)}</p>
    <p><b>Thời gian:</b> {timestamp}</p>
</div>
"""

    # ================= VULNERABILITIES =================
    report_html += "<h2>Danh sách lỗ hổng phát hiện</h2>"

    if not vulns:
        report_html += "<p><i>Không phát hiện lỗ hổng.</i></p>"
    else:
        for v in vulns:
            report_html += f"""
<div class="vuln-card">
    <h3>{html.escape(v.get('type', 'Unknown'))}</h3>
    <p><b>URL:</b> {html.escape(v.get('url', ''))}</p>
    <p><b>Tham số:</b> {html.escape(v.get('parameter', ''))} ({html.escape(v.get('method', ''))})</p>
    <p><b>Payload mẫu:</b>
        <code>{html.escape(v.get('payload', 'N/A'))}</code>
    </p>
</div>
"""

    # ================= DUMPED DATA =================
    if dumped_data:
        report_html += "<h2>Dữ liệu đã khai thác</h2>"

        for db_name, tables in dumped_data.items():
            report_html += f"<h3>Database: {html.escape(str(db_name))}</h3>"

            # Trường hợp Fast_Exploit (data không phải dict table)
            if not isinstance(tables, dict):
                report_html += f"""
<div class="data-box">
{html.escape(str(tables))}
</div>
"""
                continue

            for table_name, content in tables.items():

                # Chuẩn SQLMap CSV
                if (
                    isinstance(content, dict)
                    and 'headers' in content
                    and 'records' in content
                ):
                    report_html += f"""
<h4>Table: {html.escape(table_name)} ({len(content['records'])} rows)</h4>
<table>
<tr>
"""
                    for h in content['headers']:
                        report_html += f"<th>{html.escape(str(h))}</th>"
                    report_html += "</tr>"

                    for row in content['records']:
                        report_html += "<tr>"
                        for cell in row:
                            report_html += f"<td>{html.escape(str(cell))}</td>"
                        report_html += "</tr>"

                    report_html += "</table><br>"

                else:
                    # Fallback (server_info, banner, misc)
                    report_html += f"""
<div class="data-box">
<b>{html.escape(str(table_name))}</b>: {html.escape(str(content))}
</div>
"""

    # ================= FOOTER =================
    report_html += f"""
<div class="footer">
    Generated by Ethical Web Security Suite<br>
    © {datetime.now().year}
</div>

</body>
</html>
"""

    # ================= SAVE FILE =================
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_html)

    return os.path.abspath(filename)
